[options]
data_dir = /var/lib/odoo
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons,/var/lib/odoo/addons/19.0,/usr/lib/python3/dist-packages/addons
admin_passwd = $pbkdf2-sha512$600000$xhij9D4nZGxtjXHundNaKw$.XKVzWaeVa8UiKrnonfnQyUAiEVWQVX1JCEQpD1t1b6keiz.D29oyAyKyV4wBqRNoZELDF2xawE.6fCHtfVEVQ

