[options]
admin_passwd = $pbkdf2-sha512$600000$NAZAaI3xPkfoPYewFsLYGw$NKwUYdk9O3N/XirktScBYx6jBX3YbmAO6qlfJSAx1HWXM0210cXnpRJrgzX1SH6rQ/gL0zOFtHGXUNpB.2JgQg
data_dir = /var/lib/odoo
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons,/var/lib/odoo/addons/19.0,/usr/lib/python3/dist-packages/addons
